### ISSUE TITLE
[Feature] ability to output dashboard/alerts configuration

### ISSUE THREAD

**Issue by lpmi-13** [aws-observability/amazon-managed-grafana-migrator#12]
#### Is your feature request related to a problem? Please describe

I used this tool very successfully for migrating workspaces, though during the process, I also realized that we don't currently store any "backups" of our dashboard/alert configuration. I've used other OSS tooling for dealing with dashboards in an automated way, but nothing is as slick as this one, so I was thinking about modelling something on it to get us an output of our entire workspace configuration...but if there's a way to do it in this tool, then that would be even better.

It's highly likely this isn't appropriate for the nature of this project, but I thought I'd ask anyway. 😸 

#### Describe the solution you'd like

I'd love a secondary command to output to a local directory the configuration of our dashboards and alerts. Something like:

```
amazon-managed-grafana-migrator output \
    --src g-abcdef1234.grafana-workspace.eu-central-1.amazonaws.com \
    --folder workspace-backup
```

and I suppose that would be even more useful if there were some way to configure dashboards/alerts in a fresh workspace based on local configuration (but now this is serious scope creep 😆 )

#### Describe alternatives you've considered

I've considered using other tooling like https://github.com/Beam-Connectivity/grafana-dashboard-manager, but that doesn't seem to support alerts, and it's also not as smooth of a DX as this tool.

I've also considered just rolling my own, probably _heavily_ based on the implementation here, because there are lots of nice things about it (progress in the terminal, temporary credentials, handles both dashboards and alerts).

#### Additional context

As I mentioned, I'm expecting this request won't be appropriate for this particular project, since it's only titled "amazon-managed-grafana-migrator", but no harm in asking. I'd even be willing to submit a PR myself, though I'm definitely by no means an expert Go developer.

Thanks again for this super cool tool...it saved me a _lot_ of time 👍

**Comment by lpmi-13** [comment]
oh cool! I'll definitely check that out. Thanks 🙇

**Comment by bonclay7** [comment]
Will close this for now and let's see if we can revisit in the future
