### ISSUE TITLE
[Bug]: API key expires if migrating enough resources

### ISSUE THREAD

**Issue by andresgalindo-stripe** [aws-observability/amazon-managed-grafana-migrator#14]
### Did you search for similar issues before submitting?

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-observability/amazon-managed-grafana-migrator/issues) and didn't find any.

### Release version

0.1.3

### Is it a permission issue?

- [X] I have a valid [AWS CLI session](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html).
- [X] I'm using an IAM role with [the necessary permissions](../../README).
- [X] If migrating from a Grafana server, I used an active API key with ADMIN permissions.

### What is your environment, configuration and the example used?

Grafana v8.4.7 -> Grafana v9.4.7

Get this error:
```
	warning: status: 401, body: {"message":"Expired API key"}
```

**Comment by bonclay7** [comment]
Thanks submitting this

**Comment by bonclay7** [comment]
Should be solved by https://github.com/aws-observability/amazon-managed-grafana-migrator/releases/tag/v0.1.7, let me know
