### ISSUE TITLE
[Bug]: grafana go sdk cannot unmarshal number -1 into Go struct field FolderDashboardSearchResponse.folderId of type uint

### ISSUE THREAD

**Issue by sjoukedv** [aws-observability/amazon-managed-grafana-migrator#21]
### Did you search for similar issues before submitting?

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-observability/amazon-managed-grafana-migrator/issues) and didn't find any.

### Release version

0.1.9

### Is it a permission issue?

- [X] I have a valid [AWS CLI session](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html).
- [X] I'm using an IAM role with [the necessary permissions](../../README).
- [X] If migrating from a Grafana server, I used an active API key with ADMIN permissions.

### What is your environment, configuration and the example used?

Two grafana 8.4 instances trying to migrate from src to dst in order to upgrade the 'secondary' workspace first and be able to validate 9.4 works for us.

### Additional Information

`migrate` throws an error for migrating dashboards. Seems to be thrown by https://github.com/aws-observability/amazon-managed-grafana-migrator/blob/main/internal/pkg/app/dashboards.go#L13

```sh
✔ Migrated 6 folders

Migrating dashboards:

Removing temporary API key for g-<src>

Removing temporary API key for g-<dst>
error: json: cannot unmarshal number -1 into Go struct field FolderDashboardSearchResponse.folderId of type uint
```

**Comment by bonclay7** [comment]
Hey there, seems like one of your folders got somehow a negative id, Did the migration completed all the folders at least?

**Comment by sjoukedv** [comment]
> Hey there, seems like one of your folders got somehow a negative id, Did the migration completed all the folders at least?

No, it did not. Some things seemed to be corrupted with the Grafana instance. After a fresh install this worked perfectly fine again. Can we catch the error, log it, and continue the rest of the migration?

**Comment by bonclay7** [comment]
Fixing this is a bit more delicate than I thought. I'm unsure of the state of the objects after one of those errors is thrown. 

From the client used here
https://github.com/grafana/grafana-api-golang-client/blob/master/client.go#L149-L152

seems like nothing is returned if the parsing fails. So the fix has to be upstream (maybe just a type change [here](https://github.com/grafana/grafana-api-golang-client/blob/master/folder_dashboard_search.go#L9)

1/ Do you have a way to reproduce that error?
2/ would it make sense to open this issue on the [sdk repo](https://github.com/grafana/grafana-api-golang-client/issues)? 


What we can do so far is catch that error, still failing but with a clearer message for now
