### ISSUE TITLE
EC2 Grafana(v9.2.0) to Amazon Manage Grafana(v9.4.7) dashboard transfer issue

### ISSUE THREAD

**Issue by ruchilbshah** [aws-observability/amazon-managed-grafana-migrator#22]
### Did you search for similar issues before submitting?

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-observability/amazon-managed-grafana-migrator/issues) and didn't find any.

### Release version

go install github.com/aws-observability/amazon-managed-grafana-migrator@latest

### Is it a permission issue?

- [X] I have a valid [AWS CLI session](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html).
- [X] I'm using an IAM role with [the necessary permissions](../../README).
- [X] If migrating from a Grafana server, I used an active API key with ADMIN permissions.

### What is your environment, configuration and the example used?

Getting error while transfering EC2 Grafana(v9.2.0) to Amazon Manage Grafana(v9.4.7) 

### Additional Information

```shell
Cureently we are using in-house grafana with AWS EC2 instances and we are planning to tansfer to AMG (amazon manage grafana) and getting dail tcp : lookup no such host error.
```

**Comment by bonclay7** [comment]
seems like a networking issue. Are you able to to curl your source grafana instance using the one of the APIs? and what command did you use with the migrator (you can omit the full url/api key)

**Comment by bonclay7** [comment]
```
curl -H "Authorization: Bearer API_KEY" https://GRAFANA_DNS_NAME/api/dashboards/home
```
